key: 31alKp2rgT1BNydkVo6GZLkzRqP+4/KHO567Go0iMbuEk7c1SqYd6e8jLbUMVRi1RlXbzIjiB3/h1zK9BC9DomH3e4n3ke0lHtHsIu/I8BqJymR2PvhmX86aGb3bkW4e1ogLRyEvs7shoFvwXMTe9rdSYvEDlhLOy7g+cVhjVcEx5WjrYUbw7T8qZXBQXjQ446hkhfe+zkesLrBuk3tg9ORhK6xsMrlU6LjZVId603rxcipYwmD/zAObZEJ39D1o/jBf7vPydF+KyOOtCbyScpnitAD/YEeDCh19KjYbMZfyViLva0kojYGJNzytdTcBgtkcDIokQYa2ps/f2iLVuLPcssbv0xv0oBW2mqk3mCJgUt2oboM0GlmaSAR9HvDIhIPyp+VVADpfpJOp2ZizOrbBe4p76J155/KOAc7LZLqeM9NYxHcvH1pmcELe8Cxlcw5nYvVjqKTZt629yK2CfcxFhiyHPitnOjN34YhKC2R+5hqcIAJeDBCxnsDprXmpYb8wYS0DsLpQhq1ABgZP0wVqiy1bWzCPG0akbjbBQZzINWNnTsqoUObPUaTjCTlCxexB2LlENWf2dJ7muG8osURKe1oyHMx6SZ1NhAm3TkI/zRbn8xlveMCbxP+hCjspq2dmqD5QfbsvAtqT5NIk7HUnngOO+dexc0fE6hNP6bzGp9EVS3g0c0RSlNWQ4XDub9cfyC/pkrdZIwvGWp0HoLg3pn35w6FfJr+XvnZq4QM3FO5do/CZnSiK19rTo84rRiBaeDSyNFbNEzgU7mlS3snUzIgkMP3O1ALEzxXX/KVoiTQAqIJeVOGSSjJU1XXEPONH8C/s3M+TP+J69k18hMx6YciYMjI8ChX/+/fhoLP7Y2cGbpcejify0FtobQiSKTNrQcEwJ8u+aMzOAiqVjkho4oVtv3I9h9plwGp68VDk0JHnndWi98SrD8uXTGl9mHAYAyJMNorzHc7LjLh1wUq6tTnR4YTIO51k5vL+WTpdmyShvH4jANmjpU41WTWK
tags:
  Name: test
  appName: ecs
  projectName: snappyflow-app
metrics:
  plugins:
    - name: jvmjolokia
      enabled: true
      interval: 60
      config:
        ip: 127.0.0.1
        protocol: http
        port: 8778
        context: jolokia
        monitorDeadlocks: false
        deadLockMonitoringInterval: 300
