key: 9zWeiKJwcdnK+4BUIDrXeMLCYQNPu8L2aPsLHkilVmoiGlnmRyTZAG5CMy1G0eMffOB5/uEwYxwnn9qB/RkCM6YL6wcJv9YVSW23oNwwPx8oVurb+gFT+++RvkWqvJe5glHQAvkHAu4WZeUF72Q9TxziINSLDG06Emv7gbC5pnPm8/YIHooidAjfT4W5D3KpAwATiLmkkPoh6VLLQyD1PB/QnzBXIDPAAnUdF5wONoefaJ0aBot3fuRZdedT4aZWv9iGp6Z48IL/LLnGbBL/l9be+xSzxM4e6IJl9CZxhX9QskHshLIvmYjpMeUL8uA1LShx8n5O92WOBXKz/34aNOlt4Su5rPo91EN5SK7fuKrR8BuIDkELN9lD84AsfGcgFWuaeMO/yKgKN5uzMBT/omHE7CcINZ/tSTg+ZjA1XraOifo1R3IWFG9mnNiUEkJ6X8nQs0KsoEImlsci2ueCuvPLiAZejRo5ZNy0n+dbcy8y/f4JAtq4QMqN6KKWLP5LZ8h8btaz05lrBn5tQf/DHnwFi1ebDivnNRze4kTgM6e3cQO9Q/YlbMFYPom/wLSx7r8D/l1At+L0azKRhQ2riML86Dr9sWNC0zbabszwN9kHQa0GqR096NZyEmaKl5EgIyn+p0TSGKJfmMLc6F9NohcL7WyrfBfEq4tgXPI1GzXf7PrVdPTEttxno58NxVdTu9ec0rWftUr66oPkf+pd+W55aYF+8eRUnkDeVccUhLHVysUiOY7O9qdQoZ4bHTTvlhvRCyRRmhS+gNPALroq8mEoPfSjy9K3ai9BA+0xow/A5QrFG3/f+7fMapqUAJYi8gc+1dA6wQ18m1sspcxuADvBLx2M5UfQqkkvu2dDjFkZn1WuP0vd0POmOG/pSBDnxd4w6a+AbOm+QMSml7SIyA==
tags:
  Name: test
  appName: ecs
  projectName: snappyflow-app
metrics:
  plugins:
    - name: jvmjolokia
      enabled: true
      interval: 60
      config:
        ip: 127.0.0.1
        protocol: http
        port: 8778
        context: jolokia
        monitorDeadlocks: false
        deadLockMonitoringInterval: 300
